// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: amp.proto

package amp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AMF (ADS Mail Format) is the inner, encrypted structure
type AMFPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Subject         string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	TextBody        string                 `protobuf:"bytes,2,opt,name=text_body,json=textBody,proto3" json:"text_body,omitempty"`
	HtmlBody        string                 `protobuf:"bytes,3,opt,name=html_body,json=htmlBody,proto3" json:"html_body,omitempty"`
	Attachments     []*Attachment          `protobuf:"bytes,4,rep,name=attachments,proto3" json:"attachments,omitempty"`
	ExtendedHeaders map[string]string      `protobuf:"bytes,5,rep,name=extended_headers,json=extendedHeaders,proto3" json:"extended_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AMFPayload) Reset() {
	*x = AMFPayload{}
	mi := &file_amp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMFPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMFPayload) ProtoMessage() {}

func (x *AMFPayload) ProtoReflect() protoreflect.Message {
	mi := &file_amp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMFPayload.ProtoReflect.Descriptor instead.
func (*AMFPayload) Descriptor() ([]byte, []int) {
	return file_amp_proto_rawDescGZIP(), []int{0}
}

func (x *AMFPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *AMFPayload) GetTextBody() string {
	if x != nil {
		return x.TextBody
	}
	return ""
}

func (x *AMFPayload) GetHtmlBody() string {
	if x != nil {
		return x.HtmlBody
	}
	return ""
}

func (x *AMFPayload) GetAttachments() []*Attachment {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *AMFPayload) GetExtendedHeaders() map[string]string {
	if x != nil {
		return x.ExtendedHeaders
	}
	return nil
}

type Attachment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attachment) Reset() {
	*x = Attachment{}
	mi := &file_amp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attachment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attachment) ProtoMessage() {}

func (x *Attachment) ProtoReflect() protoreflect.Message {
	mi := &file_amp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attachment.ProtoReflect.Descriptor instead.
func (*Attachment) Descriptor() ([]byte, []int) {
	return file_amp_proto_rawDescGZIP(), []int{1}
}

func (x *Attachment) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Attachment) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Attachment) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Attachment) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// AMP Headers are unencrypted metadata for routing
type AMPHeaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderDid     string                 `protobuf:"bytes,1,opt,name=sender_did,json=senderDid,proto3" json:"sender_did,omitempty"`          // e.g., did:aftersmtp:domain:sender
	RecipientDid  string                 `protobuf:"bytes,2,opt,name=recipient_did,json=recipientDid,proto3" json:"recipient_did,omitempty"` // e.g., did:aftersmtp:domain:recipient
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix epoch
	MessageId     string                 `protobuf:"bytes,4,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`          // UUID or Hash
	PreviousHop   string                 `protobuf:"bytes,5,opt,name=previous_hop,json=previousHop,proto3" json:"previous_hop,omitempty"`    // DID of the previous relay (for tracking)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AMPHeaders) Reset() {
	*x = AMPHeaders{}
	mi := &file_amp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMPHeaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMPHeaders) ProtoMessage() {}

func (x *AMPHeaders) ProtoReflect() protoreflect.Message {
	mi := &file_amp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMPHeaders.ProtoReflect.Descriptor instead.
func (*AMPHeaders) Descriptor() ([]byte, []int) {
	return file_amp_proto_rawDescGZIP(), []int{2}
}

func (x *AMPHeaders) GetSenderDid() string {
	if x != nil {
		return x.SenderDid
	}
	return ""
}

func (x *AMPHeaders) GetRecipientDid() string {
	if x != nil {
		return x.RecipientDid
	}
	return ""
}

func (x *AMPHeaders) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AMPHeaders) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AMPHeaders) GetPreviousHop() string {
	if x != nil {
		return x.PreviousHop
	}
	return ""
}

// The actual structure sent over the wire (QUIC/gRPC)
type AMPMessage struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Headers *AMPHeaders            `protobuf:"bytes,1,opt,name=headers,proto3" json:"headers,omitempty"`
	// The AMFPayload encrypted with the recipient's public key (e.g., X25519 + AES-GCM)
	EncryptedPayload []byte `protobuf:"bytes,2,opt,name=encrypted_payload,json=encryptedPayload,proto3" json:"encrypted_payload,omitempty"`
	// Ephemeral public key used by the sender for this specific encryption
	EphemeralPublicKey []byte `protobuf:"bytes,3,opt,name=ephemeral_public_key,json=ephemeralPublicKey,proto3" json:"ephemeral_public_key,omitempty"`
	// Ed25519 signature of the headers + encrypted_payload, signed by sender_did's private key
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
	// Optional blockchain proof or transaction ID anchoring this message's transit
	BlockchainProof string `protobuf:"bytes,5,opt,name=blockchain_proof,json=blockchainProof,proto3" json:"blockchain_proof,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AMPMessage) Reset() {
	*x = AMPMessage{}
	mi := &file_amp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMPMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMPMessage) ProtoMessage() {}

func (x *AMPMessage) ProtoReflect() protoreflect.Message {
	mi := &file_amp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMPMessage.ProtoReflect.Descriptor instead.
func (*AMPMessage) Descriptor() ([]byte, []int) {
	return file_amp_proto_rawDescGZIP(), []int{3}
}

func (x *AMPMessage) GetHeaders() *AMPHeaders {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *AMPMessage) GetEncryptedPayload() []byte {
	if x != nil {
		return x.EncryptedPayload
	}
	return nil
}

func (x *AMPMessage) GetEphemeralPublicKey() []byte {
	if x != nil {
		return x.EphemeralPublicKey
	}
	return nil
}

func (x *AMPMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AMPMessage) GetBlockchainProof() string {
	if x != nil {
		return x.BlockchainProof
	}
	return ""
}

type DeliveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ReceiptHash   string                 `protobuf:"bytes,3,opt,name=receipt_hash,json=receiptHash,proto3" json:"receipt_hash,omitempty"` // Cryptographic proof of receipt
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryResponse) Reset() {
	*x = DeliveryResponse{}
	mi := &file_amp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryResponse) ProtoMessage() {}

func (x *DeliveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_amp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryResponse.ProtoReflect.Descriptor instead.
func (*DeliveryResponse) Descriptor() ([]byte, []int) {
	return file_amp_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliveryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryResponse) GetReceiptHash() string {
	if x != nil {
		return x.ReceiptHash
	}
	return ""
}

var File_amp_proto protoreflect.FileDescriptor

const file_amp_proto_rawDesc = "" +
	"\n" +
	"\tamp.proto\x12\x03amp\"\xa8\x02\n" +
	"\n" +
	"AMFPayload\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\ttext_body\x18\x02 \x01(\tR\btextBody\x12\x1b\n" +
	"\thtml_body\x18\x03 \x01(\tR\bhtmlBody\x121\n" +
	"\vattachments\x18\x04 \x03(\v2\x0f.amp.AttachmentR\vattachments\x12O\n" +
	"\x10extended_headers\x18\x05 \x03(\v2$.amp.AMFPayload.ExtendedHeadersEntryR\x0fextendedHeaders\x1aB\n" +
	"\x14ExtendedHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"s\n" +
	"\n" +
	"Attachment\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\"\xb0\x01\n" +
	"\n" +
	"AMPHeaders\x12\x1d\n" +
	"\n" +
	"sender_did\x18\x01 \x01(\tR\tsenderDid\x12#\n" +
	"\rrecipient_did\x18\x02 \x01(\tR\frecipientDid\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"message_id\x18\x04 \x01(\tR\tmessageId\x12!\n" +
	"\fprevious_hop\x18\x05 \x01(\tR\vpreviousHop\"\xdf\x01\n" +
	"\n" +
	"AMPMessage\x12)\n" +
	"\aheaders\x18\x01 \x01(\v2\x0f.amp.AMPHeadersR\aheaders\x12+\n" +
	"\x11encrypted_payload\x18\x02 \x01(\fR\x10encryptedPayload\x120\n" +
	"\x14ephemeral_public_key\x18\x03 \x01(\fR\x12ephemeralPublicKey\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\x12)\n" +
	"\x10blockchain_proof\x18\x05 \x01(\tR\x0fblockchainProof\"t\n" +
	"\x10DeliveryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\freceipt_hash\x18\x03 \x01(\tR\vreceiptHash2E\n" +
	"\tAMPServer\x128\n" +
	"\x0eDeliverMessage\x12\x0f.amp.AMPMessage\x1a\x15.amp.DeliveryResponseBPZNgithub.com/afterdarksys/go-emailservice-ads/internal/aftersmtplib/protocol/ampb\x06proto3"

var (
	file_amp_proto_rawDescOnce sync.Once
	file_amp_proto_rawDescData []byte
)

func file_amp_proto_rawDescGZIP() []byte {
	file_amp_proto_rawDescOnce.Do(func() {
		file_amp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amp_proto_rawDesc), len(file_amp_proto_rawDesc)))
	})
	return file_amp_proto_rawDescData
}

var file_amp_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_amp_proto_goTypes = []any{
	(*AMFPayload)(nil),       // 0: amp.AMFPayload
	(*Attachment)(nil),       // 1: amp.Attachment
	(*AMPHeaders)(nil),       // 2: amp.AMPHeaders
	(*AMPMessage)(nil),       // 3: amp.AMPMessage
	(*DeliveryResponse)(nil), // 4: amp.DeliveryResponse
	nil,                      // 5: amp.AMFPayload.ExtendedHeadersEntry
}
var file_amp_proto_depIdxs = []int32{
	1, // 0: amp.AMFPayload.attachments:type_name -> amp.Attachment
	5, // 1: amp.AMFPayload.extended_headers:type_name -> amp.AMFPayload.ExtendedHeadersEntry
	2, // 2: amp.AMPMessage.headers:type_name -> amp.AMPHeaders
	3, // 3: amp.AMPServer.DeliverMessage:input_type -> amp.AMPMessage
	4, // 4: amp.AMPServer.DeliverMessage:output_type -> amp.DeliveryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_amp_proto_init() }
func file_amp_proto_init() {
	if File_amp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amp_proto_rawDesc), len(file_amp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_amp_proto_goTypes,
		DependencyIndexes: file_amp_proto_depIdxs,
		MessageInfos:      file_amp_proto_msgTypes,
	}.Build()
	File_amp_proto = out.File
	file_amp_proto_goTypes = nil
	file_amp_proto_depIdxs = nil
}
