// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: amp.proto

package amp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AMPServer_DeliverMessage_FullMethodName = "/amp.AMPServer/DeliverMessage"
)

// AMPServerClient is the client API for AMPServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for Server-to-Server and Client-to-Server
type AMPServerClient interface {
	// Deliver a message. If the signature is invalid, it is rejected immediately.
	DeliverMessage(ctx context.Context, in *AMPMessage, opts ...grpc.CallOption) (*DeliveryResponse, error)
}

type aMPServerClient struct {
	cc grpc.ClientConnInterface
}

func NewAMPServerClient(cc grpc.ClientConnInterface) AMPServerClient {
	return &aMPServerClient{cc}
}

func (c *aMPServerClient) DeliverMessage(ctx context.Context, in *AMPMessage, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, AMPServer_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AMPServerServer is the server API for AMPServer service.
// All implementations must embed UnimplementedAMPServerServer
// for forward compatibility.
//
// Service definition for Server-to-Server and Client-to-Server
type AMPServerServer interface {
	// Deliver a message. If the signature is invalid, it is rejected immediately.
	DeliverMessage(context.Context, *AMPMessage) (*DeliveryResponse, error)
	mustEmbedUnimplementedAMPServerServer()
}

// UnimplementedAMPServerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAMPServerServer struct{}

func (UnimplementedAMPServerServer) DeliverMessage(context.Context, *AMPMessage) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedAMPServerServer) mustEmbedUnimplementedAMPServerServer() {}
func (UnimplementedAMPServerServer) testEmbeddedByValue()                   {}

// UnsafeAMPServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AMPServerServer will
// result in compilation errors.
type UnsafeAMPServerServer interface {
	mustEmbedUnimplementedAMPServerServer()
}

func RegisterAMPServerServer(s grpc.ServiceRegistrar, srv AMPServerServer) {
	// If the following call panics, it indicates UnimplementedAMPServerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AMPServer_ServiceDesc, srv)
}

func _AMPServer_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AMPMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AMPServerServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AMPServer_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AMPServerServer).DeliverMessage(ctx, req.(*AMPMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AMPServer_ServiceDesc is the grpc.ServiceDesc for AMPServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AMPServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amp.AMPServer",
	HandlerType: (*AMPServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeliverMessage",
			Handler:    _AMPServer_DeliverMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "amp.proto",
}
