apiVersion: v1
kind: Service
metadata:
  name: smtp-perimeter
  namespace: mail-system
  labels:
    app: smtp
    component: perimeter-mta
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: smtp
    component: perimeter-mta
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: smtp-perimeter-metrics
  namespace: mail-system
  labels:
    app: smtp
    component: perimeter-mta
spec:
  type: ClusterIP
  selector:
    app: smtp
    component: perimeter-mta
  ports:
  - name: smtp
    port: 25
    targetPort: 25
    protocol: TCP
