// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: client.proto

package client

import (
	context "context"
	amp "github.com/afterdarksys/go-emailservice-ads/internal/aftersmtplib/protocol/amp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClientAPI_RequestChallenge_FullMethodName = "/client.ClientAPI/RequestChallenge"
	ClientAPI_Authenticate_FullMethodName     = "/client.ClientAPI/Authenticate"
	ClientAPI_DispatchMessage_FullMethodName  = "/client.ClientAPI/DispatchMessage"
	ClientAPI_FetchInbox_FullMethodName       = "/client.ClientAPI/FetchInbox"
	ClientAPI_RegisterIdentity_FullMethodName = "/client.ClientAPI/RegisterIdentity"
)

// ClientAPIClient is the client API for ClientAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ClientAPI provides authenticated management and inbox access for AfterSMTP DIDs
type ClientAPIClient interface {
	// 1. Authentication
	// Step A: Request a cryptographic challenge for a specific DID
	RequestChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error)
	// Step B: Submit the challenge signed by the DID's Ed25519 private key to receive a JWT session token
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// 2. Messaging
	// Securely dispatch a message via the server (the client still encrypts and signs the payload locally)
	DispatchMessage(ctx context.Context, in *amp.AMPMessage, opts ...grpc.CallOption) (*amp.DeliveryResponse, error)
	// Fetch inbox messages intended for this DID
	FetchInbox(ctx context.Context, in *InboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[amp.AMPMessage], error)
	// 3. Management
	// Register a new alias or identity linking onto the ledger
	RegisterIdentity(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*IdentityResponse, error)
}

type clientAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewClientAPIClient(cc grpc.ClientConnInterface) ClientAPIClient {
	return &clientAPIClient{cc}
}

func (c *clientAPIClient) RequestChallenge(ctx context.Context, in *ChallengeRequest, opts ...grpc.CallOption) (*ChallengeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChallengeResponse)
	err := c.cc.Invoke(ctx, ClientAPI_RequestChallenge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ClientAPI_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) DispatchMessage(ctx context.Context, in *amp.AMPMessage, opts ...grpc.CallOption) (*amp.DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(amp.DeliveryResponse)
	err := c.cc.Invoke(ctx, ClientAPI_DispatchMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientAPIClient) FetchInbox(ctx context.Context, in *InboxRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[amp.AMPMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClientAPI_ServiceDesc.Streams[0], ClientAPI_FetchInbox_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InboxRequest, amp.AMPMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientAPI_FetchInboxClient = grpc.ServerStreamingClient[amp.AMPMessage]

func (c *clientAPIClient) RegisterIdentity(ctx context.Context, in *IdentityRequest, opts ...grpc.CallOption) (*IdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdentityResponse)
	err := c.cc.Invoke(ctx, ClientAPI_RegisterIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientAPIServer is the server API for ClientAPI service.
// All implementations must embed UnimplementedClientAPIServer
// for forward compatibility.
//
// ClientAPI provides authenticated management and inbox access for AfterSMTP DIDs
type ClientAPIServer interface {
	// 1. Authentication
	// Step A: Request a cryptographic challenge for a specific DID
	RequestChallenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error)
	// Step B: Submit the challenge signed by the DID's Ed25519 private key to receive a JWT session token
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	// 2. Messaging
	// Securely dispatch a message via the server (the client still encrypts and signs the payload locally)
	DispatchMessage(context.Context, *amp.AMPMessage) (*amp.DeliveryResponse, error)
	// Fetch inbox messages intended for this DID
	FetchInbox(*InboxRequest, grpc.ServerStreamingServer[amp.AMPMessage]) error
	// 3. Management
	// Register a new alias or identity linking onto the ledger
	RegisterIdentity(context.Context, *IdentityRequest) (*IdentityResponse, error)
	mustEmbedUnimplementedClientAPIServer()
}

// UnimplementedClientAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientAPIServer struct{}

func (UnimplementedClientAPIServer) RequestChallenge(context.Context, *ChallengeRequest) (*ChallengeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestChallenge not implemented")
}
func (UnimplementedClientAPIServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedClientAPIServer) DispatchMessage(context.Context, *amp.AMPMessage) (*amp.DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DispatchMessage not implemented")
}
func (UnimplementedClientAPIServer) FetchInbox(*InboxRequest, grpc.ServerStreamingServer[amp.AMPMessage]) error {
	return status.Error(codes.Unimplemented, "method FetchInbox not implemented")
}
func (UnimplementedClientAPIServer) RegisterIdentity(context.Context, *IdentityRequest) (*IdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterIdentity not implemented")
}
func (UnimplementedClientAPIServer) mustEmbedUnimplementedClientAPIServer() {}
func (UnimplementedClientAPIServer) testEmbeddedByValue()                   {}

// UnsafeClientAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientAPIServer will
// result in compilation errors.
type UnsafeClientAPIServer interface {
	mustEmbedUnimplementedClientAPIServer()
}

func RegisterClientAPIServer(s grpc.ServiceRegistrar, srv ClientAPIServer) {
	// If the following call panics, it indicates UnimplementedClientAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientAPI_ServiceDesc, srv)
}

func _ClientAPI_RequestChallenge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChallengeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).RequestChallenge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_RequestChallenge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).RequestChallenge(ctx, req.(*ChallengeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_DispatchMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(amp.AMPMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).DispatchMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_DispatchMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).DispatchMessage(ctx, req.(*amp.AMPMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClientAPI_FetchInbox_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InboxRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClientAPIServer).FetchInbox(m, &grpc.GenericServerStream[InboxRequest, amp.AMPMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClientAPI_FetchInboxServer = grpc.ServerStreamingServer[amp.AMPMessage]

func _ClientAPI_RegisterIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientAPIServer).RegisterIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientAPI_RegisterIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientAPIServer).RegisterIdentity(ctx, req.(*IdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientAPI_ServiceDesc is the grpc.ServiceDesc for ClientAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "client.ClientAPI",
	HandlerType: (*ClientAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestChallenge",
			Handler:    _ClientAPI_RequestChallenge_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _ClientAPI_Authenticate_Handler,
		},
		{
			MethodName: "DispatchMessage",
			Handler:    _ClientAPI_DispatchMessage_Handler,
		},
		{
			MethodName: "RegisterIdentity",
			Handler:    _ClientAPI_RegisterIdentity_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchInbox",
			Handler:       _ClientAPI_FetchInbox_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "client.proto",
}
