#!/bin/bash
# ADS PreMail Setup Script
# Sets up nftables, database, and configuration

set -e

echo "========================================="
echo "  ADS PreMail Setup Script"
echo "  Transparent SMTP Protection Layer"
echo "========================================="
echo

# Check if running as root
if [ "$EUID" -ne 0 ]; then
   echo "ERROR: This script must be run as root (for nftables setup)"
   echo "Usage: sudo $0"
   exit 1
fi

# Get the actual user (not root when using sudo)
ACTUAL_USER=${SUDO_USER:-$USER}
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "[1/6] Checking prerequisites..."

# Check for required commands
MISSING_DEPS=0

if ! command -v nft &> /dev/null; then
    echo "  ✗ nftables not found"
    MISSING_DEPS=1
else
    echo "  ✓ nftables found"
fi

if ! command -v psql &> /dev/null; then
    echo "  ✗ PostgreSQL client not found"
    MISSING_DEPS=1
else
    echo "  ✓ PostgreSQL client found"
fi

if ! command -v go &> /dev/null; then
    echo "  ✗ Go not found"
    MISSING_DEPS=1
else
    echo "  ✓ Go found ($(go version))"
fi

if [ $MISSING_DEPS -eq 1 ]; then
    echo
    echo "ERROR: Missing required dependencies"
    echo "Install with: sudo apt install nftables postgresql-client golang"
    exit 1
fi

echo
echo "[2/6] Building ADS PreMail..."
cd "$PROJECT_DIR"
sudo -u "$ACTUAL_USER" go build -o bin/adspremail ./cmd/adspremail
if [ $? -eq 0 ]; then
    echo "  ✓ Built successfully: bin/adspremail"
else
    echo "  ✗ Build failed"
    exit 1
fi

echo
echo "[3/6] Setting up PostgreSQL database..."

# Prompt for database details
read -p "PostgreSQL host [localhost]: " DB_HOST
DB_HOST=${DB_HOST:-localhost}

read -p "PostgreSQL port [5432]: " DB_PORT
DB_PORT=${DB_PORT:-5432}

read -p "PostgreSQL admin user [postgres]: " ADMIN_USER
ADMIN_USER=${ADMIN_USER:-postgres}

read -p "Database name [emailservice]: " DB_NAME
DB_NAME=${DB_NAME:-emailservice}

read -p "ADS PreMail database user [premail]: " DB_USER
DB_USER=${DB_USER:-premail}

read -s -p "Password for user '$DB_USER': " DB_PASSWORD
echo

# Create database and user
echo "  Creating database and user..."
sudo -u postgres psql -h "$DB_HOST" -p "$DB_PORT" <<EOF || echo "Database may already exist"
CREATE DATABASE $DB_NAME;
CREATE USER $DB_USER WITH PASSWORD '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
EOF

if [ $? -eq 0 ]; then
    echo "  ✓ Database setup complete"
else
    echo "  ! Database setup had warnings (may already exist)"
fi

# Save database credentials
echo "  Saving database credentials to .env file..."
cat > "$PROJECT_DIR/.env.premail" <<EOF
# ADS PreMail Environment Variables
PREMAIL_DB_PASSWORD='$DB_PASSWORD'
# DNSSCIENCE_API_KEY='your_api_key_here'
EOF

chmod 600 "$PROJECT_DIR/.env.premail"
echo "  ✓ Credentials saved to .env.premail"

echo
echo "[4/6] Setting up nftables..."

# Create nftables configuration
NFTABLES_CONF="/etc/nftables.d/adspremail.conf"
mkdir -p /etc/nftables.d

cat > "$NFTABLES_CONF" <<'EOF'
#!/usr/sbin/nft -f
# ADS PreMail nftables configuration
# Generated by setup-adspremail.sh

table inet filter {
    # IP sets with automatic timeout
    set adspremail_blacklist {
        type ipv4_addr
        flags timeout
        timeout 24h
    }

    set adspremail_ratelimit {
        type ipv4_addr
        flags timeout
        timeout 1h
    }

    set adspremail_monitor {
        type ipv4_addr
        flags timeout
        timeout 30m
    }

    # Prerouting chain for filtering
    chain adspremail_prerouting {
        type filter hook prerouting priority 0;

        # Drop blacklisted IPs immediately
        ip saddr @adspremail_blacklist drop

        # Mark packets for different threat levels
        ip saddr @adspremail_ratelimit meta mark set 0x3
        ip saddr @adspremail_monitor meta mark set 0x1
    }

    # Input chain for rate limiting
    chain adspremail_input {
        type filter hook input priority 0;

        # Rate limit tarpitted IPs (1 packet/minute)
        meta mark 0x3 limit rate 1/minute accept
        meta mark 0x3 drop
    }
}

# NAT table for transparent proxy
table inet nat {
    chain prerouting {
        type nat hook prerouting priority -100;

        # Redirect incoming port 25 to ADS PreMail on port 2525
        tcp dport 25 dnat to :2525
    }
}
EOF

echo "  ✓ Created nftables configuration: $NFTABLES_CONF"

# Load nftables rules
echo "  Loading nftables rules..."
nft -f "$NFTABLES_CONF"
if [ $? -eq 0 ]; then
    echo "  ✓ nftables rules loaded successfully"
else
    echo "  ✗ Failed to load nftables rules"
    exit 1
fi

# Make nftables persistent
if [ -f /etc/nftables.conf ]; then
    if ! grep -q "include \"$NFTABLES_CONF\"" /etc/nftables.conf; then
        echo "include \"$NFTABLES_CONF\"" >> /etc/nftables.conf
        echo "  ✓ Added to /etc/nftables.conf for persistence"
    fi
fi

echo
echo "[5/6] Creating configuration file..."

# Update config file with database settings
cd "$PROJECT_DIR"
if [ ! -f config-premail.yaml ]; then
    # Initialize config
    sudo -u "$ACTUAL_USER" ./bin/adspremail --init --config config-premail.yaml
    echo "  ✓ Created default configuration"
fi

# Update database settings in config
sed -i.bak \
    -e "s/host: \"localhost\"/host: \"$DB_HOST\"/" \
    -e "s/port: 5432/port: $DB_PORT/" \
    -e "s/database: \"emailservice\"/database: \"$DB_NAME\"/" \
    -e "s/user: \"premail\"/user: \"$DB_USER\"/" \
    config-premail.yaml

echo "  ✓ Updated configuration file"

echo
echo "[6/6] Creating systemd service..."

# Create systemd service file
SERVICE_FILE="/etc/systemd/system/adspremail.service"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=ADS PreMail - Transparent SMTP Protection Layer
After=network.target postgresql.service nftables.service
Wants=postgresql.service nftables.service

[Service]
Type=simple
User=root
WorkingDirectory=$PROJECT_DIR
EnvironmentFile=$PROJECT_DIR/.env.premail
ExecStart=$PROJECT_DIR/bin/adspremail --config $PROJECT_DIR/config-premail.yaml
Restart=always
RestartSec=10

# Security hardening
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$PROJECT_DIR

[Install]
WantedBy=multi-user.target
EOF

echo "  ✓ Created systemd service: $SERVICE_FILE"

# Reload systemd
systemctl daemon-reload
echo "  ✓ Reloaded systemd"

echo
echo "========================================="
echo "  Setup Complete!"
echo "========================================="
echo
echo "Next steps:"
echo
echo "1. Review and customize the configuration:"
echo "   nano $PROJECT_DIR/config-premail.yaml"
echo
echo "2. Configure your backend mail server:"
echo "   - Ensure it listens on port 25 (or custom port)"
echo "   - Bind to localhost only if ADS PreMail is on same server"
echo
echo "3. Start ADS PreMail:"
echo "   sudo systemctl start adspremail"
echo
echo "4. Enable auto-start on boot:"
echo "   sudo systemctl enable adspremail"
echo
echo "5. Check status:"
echo "   sudo systemctl status adspremail"
echo
echo "6. View logs:"
echo "   sudo journalctl -u adspremail -f"
echo
echo "7. Monitor nftables sets:"
echo "   sudo nft list set inet filter adspremail_blacklist"
echo
echo "Configuration file: $PROJECT_DIR/config-premail.yaml"
echo "Environment variables: $PROJECT_DIR/.env.premail"
echo "nftables config: $NFTABLES_CONF"
echo "Service file: $SERVICE_FILE"
echo
echo "Database connection:"
echo "  Host: $DB_HOST:$DB_PORT"
echo "  Database: $DB_NAME"
echo "  User: $DB_USER"
echo
echo "For help, see: $PROJECT_DIR/ADS_PREMAIL_README.md"
echo
