apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: goemailservices-data
  namespace: email-system
  labels:
    app: goemailservices
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: fast-ssd
